version: latest
services:
  spring-boot-app:
    build:
      context: ./build/libs
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/reserveDatabase
      SPRING_DATASOURCE_USERNAME: 'user'
      SPRING_DATASOURCE_PASSWORD: 'pass'

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reserveDatabase
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'